language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key: f2fe1f20-1ab4-4dbf-a32b-8aecb13d04ce
    #secure: ZlM+mPCuZUx0QQlw198KGWywMYID/VTdL/hzJYQ4v+l+i0lpQ7kpFO6/3M5upv2YKZDG0EzWl6fSe3AqgfIkv/g3hPQhXBdOu9arcnXtv9ae54ikfTq8rctWRdgNxX2NjLBEiaXKoF7v9rcjgkkYJXfM/hQbLbreay5QGONkUcbz2OioAfAjEyHXB5PYbEXaXrKm80RRcLZ5ubI2nXlHhXbytUCSxFRqnxCy8TUaVuLgtTFm5a3YuYzTh9QTIhECMl/eLOgf1Yq8MYQWZgVVdWnqXFpuwXypnmrhkFuAz1lD9+vrz5ryiJW/Ig4WWgRn4D6uWwIS9qX40H8BCyK8qy20dq2NtmlJMXpwqnV+jXah6gcS7vdGXd5BfAZvyI7VYU+8U+ZrK40ESthRf+AIJ7TZfNsvDY+Il0vToANLxQjRMFlq4IqnjnHbhy9DvfIJsC3f8DZiM2+rQNlRAKknbMA/vlNqzQXHCairqGTt/gZ0xZspWCdhcgMo/ohffweEhPfx+Akwu09Ocx8LdwLqjYjouNftEan80QnFeuaUxgcXLHw4exoQ732gHY9/tggi4ZwU5vzaOIrLnpsqtXvQLiOGqUHn4n0AggDRBMbSNsHGNbWGqp/QEqk3iZZN/Y8gEeQNua1uxr90ogrFQFIWds3qTn4fnS1j4Fn09ndK7Lo=
  app: boiling-hamlet-94997
  on:
    repo: luigomez11/fullstackCapstone
